In [1]:
import opensim as osim
import numpy as np
import hyperobjects as ho
import common
import clifford as cf
import clifford.tools.g3c as g3c_tools

G3, blades_g3 = cf.Cl(3) # instantiate a 3D- GA
G3c, blades_g3c, stuff = cf.conformalize(G3)

e1, e2, e3 = blades_g3c["e1"], blades_g3c["e2"], blades_g3c["e3"]
up, down = stuff["up"], stuff["down"]
no, ni = stuff["eo"], stuff["einf"]


c:\Users\glaisne\mambaforge\envs\workspace\Lib\site-packages\numba\core\decorators.py:262: NumbaDeprecationWarning: numba.generated_jit is deprecated. Please see the documentation at: https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-generated-jit for more information and advice on a suitable replacement.
  warnings.warn(msg, NumbaDeprecationWarning)
c:\Users\glaisne\mambaforge\envs\workspace\Lib\site-packages\numba\core\decorators.py:262: NumbaDeprecationWarning: numba.generated_jit is deprecated. Please see the documentation at: https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-generated-jit for more information and advice on a suitable replacement.
  warnings.warn(msg, NumbaDeprecationWarning)
c:\Users\glaisne\mambaforge\envs\workspace\Lib\site-packages\numba\core\decorators.py:262: NumbaDeprecationWarning: numba.generated_jit is deprecated. Please see the documentation at: https://numba.readthedocs.io/en/stable/reference

In [2]:
O_in_G = g3c_tools.random_conformal_point()
I_in_B4 = g3c_tools.random_conformal_point()

G = 1
B1 = g3c_tools.random_rotation_translation_rotor()
J1_q1 = g3c_tools.random_rotation_translation_rotor()
J1_q2 = g3c_tools.random_rotation_translation_rotor()

B2 = g3c_tools.random_rotation_translation_rotor()
J2_q1 = g3c_tools.random_rotation_translation_rotor()
J2_q2 = g3c_tools.random_rotation_translation_rotor()

B3 = g3c_tools.random_rotation_translation_rotor()
J3_q1 = g3c_tools.random_rotation_translation_rotor()
J3_q2 = g3c_tools.random_rotation_translation_rotor()

B4 = g3c_tools.random_rotation_translation_rotor()

In [43]:
T_42_q1 = J2_q1*B3*J3_q1*B4
T_43_q1 = J3_q1*B4
T_G2_q1 = ~(B1*J1_q1*B2)
T_G3_q1 = ~(B1*J1_q1*B2*J2_q1*B3)

T_4G_q1 = B1*J1_q1*B2*J2_q1*B3*J3_q1*B4
T_3G_q1 = B1*J1_q1*B2*J2_q1*B3
T_2G_q1 = B1*J1_q1*B2
T_1G_q1 = B1

T_42_q2 = J2_q2*B3*J3_q2*B4
T_43_q2 = J3_q2*B4
T_G2_q2 = ~(B1*J1_q2*B2)
T_G3_q2 = ~(B1*J1_q2*B2*J2_q2*B3)
T_4G_q2 = B1*J1_q2*B2*J2_q2*B3*J3_q2*B4
T_3G_q2 = B1*J1_q2*B2*J2_q2*B3
T_2G_q2 = B1*J1_q2*B2
T_1G_q2 = B1

I_in_G_q1 = g3c_tools.apply_rotor(I_in_B4, T_4G_q1)
I_in_B2_q1 = g3c_tools.apply_rotor(I_in_B4, T_42_q1)
I_in_B3_q1 = g3c_tools.apply_rotor(I_in_B4, T_43_q1)
O_in_B2_q1 = g3c_tools.apply_rotor(O_in_G, T_G2_q1)
O_in_B3_q1 = g3c_tools.apply_rotor(O_in_G, T_G3_q1)
O_in_B4_q1 = g3c_tools.apply_rotor(O_in_G, ~T_4G_q1)

I_in_G_q2 = g3c_tools.apply_rotor(I_in_B4, T_4G_q2)
I_in_B2_q2 = g3c_tools.apply_rotor(I_in_B4, T_42_q2)
I_in_B3_q2 = g3c_tools.apply_rotor(I_in_B4, T_43_q2)
O_in_B2_q2 = g3c_tools.apply_rotor(O_in_G, T_G2_q2)
O_in_B3_q2 = g3c_tools.apply_rotor(O_in_G, T_G3_q2)
O_in_B4_q2 = g3c_tools.apply_rotor(O_in_G, ~T_4G_q2)


print(abs(I_in_B4 - O_in_B4_q1))
print(abs(I_in_B2_q1 - O_in_B2_q1))
print(abs(I_in_B3_q1 - O_in_B3_q1))
print(abs(I_in_G_q1 - O_in_G))

print(abs(I_in_B4 - O_in_B4_q2))
print(abs(I_in_B2_q2 - O_in_B2_q2))
print(abs(I_in_B3_q2 - O_in_B3_q2))
print(abs(I_in_G_q2 - O_in_G))

42.40499627794621
42.40499627794656
42.40499627794793
42.40499627794638
18.567760542054014
18.567760542054355
18.567760542054064
18.567760542053964


In [44]:
L_in_G_q1 = O_in_G^I_in_G_q1^ni
L_in_B2_q1 = g3c_tools.apply_rotor(L_in_G_q1, ~T_2G_q1)
L_in_B3_q1 = g3c_tools.apply_rotor(L_in_G_q1, ~T_3G_q1)
L_in_B4_q1 = g3c_tools.apply_rotor(L_in_G_q1, ~T_4G_q1)

L_in_G_q2 = O_in_G^I_in_G_q2^ni
L_in_B2_q2 = g3c_tools.apply_rotor(L_in_G_q2, ~T_2G_q2)
L_in_B3_q2 = g3c_tools.apply_rotor(L_in_G_q2, ~T_3G_q2)
L_in_B4_q2 = g3c_tools.apply_rotor(L_in_G_q2, ~T_4G_q2)

In [45]:
print(L_in_G_q1)
print(g3c_tools.apply_rotor(L_in_B3_q1, T_3G_q1))

(453.32367^e124) + (453.32367^e125) + (107.07193^e134) + (107.07193^e135) + (26.17924^e145) + (189.16392^e234) + (189.16392^e235) + (33.21677^e245) - (3.07856^e345)
(453.32367^e124) + (453.32367^e125) + (107.07193^e134) + (107.07193^e135) + (26.17924^e145) + (189.16392^e234) + (189.16392^e235) + (33.21677^e245) - (3.07856^e345)


In [46]:
print(L_in_B3_q1)
print(O_in_B3_q1^I_in_B3_q1^ni)
print(O_in_B3_q1^(I_in_B3_q1 - O_in_B3_q1)^ni)

(550.5123^e124) + (550.5123^e125) - (183.43288^e134) - (183.43288^e135) - (33.47027^e145) + (450.81794^e234) + (450.81794^e235) + (9.47281^e245) + (24.25264^e345)
(550.5123^e124) + (550.5123^e125) - (183.43288^e134) - (183.43288^e135) - (33.47027^e145) + (450.81794^e234) + (450.81794^e235) + (9.47281^e245) + (24.25264^e345)
(550.5123^e124) + (550.5123^e125) - (183.43288^e134) - (183.43288^e135) - (33.47027^e145) + (450.81794^e234) + (450.81794^e235) + (9.47281^e245) + (24.25264^e345)


In [130]:
print(down(O_in_B3_q1))

def point_to_np(p):
    return np.array([down(p) | e1, down(p) | e2, down(p) | e3]).astype(float)

O_in_B4_np_q1 = point_to_np(O_in_B4_q1)
O_in_B4_np_q2 = point_to_np(O_in_B4_q2)
I_in_B4_np = point_to_np(I_in_B4)

M_in_B4_q1 = L_in_B4_q1.dual()
M_in_B4_q2 = L_in_B4_q2.dual()

M_dir_in_B4_q1 = (M_in_B4_q1 | (-e1*e2))*(e1^e2) + (M_in_B4_q1 | (-e1*e3))*(e1^e3) + (M_in_B4_q1 | (-e2*e3))*(e2^e3)
M_dir_in_B4_q1_normal = M_dir_in_B4_q1 | (e1^e2^e3)
M_mom_in_B4_q1 = M_in_B4_q1 | no

M_dir_in_B4_q2 = (M_in_B4_q2 | (-e1*e2))*(e1^e2) + (M_in_B4_q2 | (-e1*e3))*(e1^e3) + (M_in_B4_q2 | (-e2*e3))*(e2^e3)
M_dir_in_B4_q2_normal = M_dir_in_B4_q2 | (e1^e2^e3)
M_mom_in_B4_q2 = M_in_B4_q2 | no

print(np.cross(I_in_B4_np, O_in_B4_np_q1))
print(M_mom_in_B4_q1)
print()

print(np.cross(I_in_B4_np, O_in_B4_np_q2))
print(M_mom_in_B4_q2)

Line_I = g3c_tools.meet(M_mom_in_B4_q1.dual(), M_mom_in_B4_q2.dual())
Line_I2 = g3c_tools.meet(M_dir_in_B4_q1_normal.dual(), M_dir_in_B4_q2_normal.dual())
# print(Line_I)
print()
print("LI2", Line_I2.normal())
print(Line_I.normal())
print(M_dir_in_B4_q1_normal)
print()

print((I_in_B4 ^ Line_I))
print("I", (down(I_in_B4).normal()))

print(I_in_B4)
print(I_in_B4 ^ L_in_B4_q1)
print(I_in_B4 ^ L_in_B4_q2)

print(np.cross(I_in_B4_np, O_in_B4_np_q2) / np.linalg.norm(I_in_B4_np - O_in_B4_np_q2))
print(L_in_B4_q2.normal())

# print(L_in_G_q1.dual())
# print(print(np.cross(I_in_B3_np_q1, O_in_B3_np_q1)))
# M_q1 = L_in_G_q1.dual() | (e1^e2)
# M_q1

(5.98402^e1) + (14.75419^e2) - (9.81651^e3)
[ -40.97255987 -452.0063922    71.94726923]
(40.97256^e1) + (452.00639^e2) - (71.94727^e3)

[73.26634446 90.07599354  5.67519505]
-(73.26634^e1) - (90.07599^e2) - (5.6752^e3)

LI2 (0.31671^e145) + (0.90971^e245) - (0.26856^e345)
(0.28925^e145) - (0.17599^e245) - (0.94094^e345)
-(19.71304^e1) - (4.15248^e2) - (37.31403^e3)

(0.0^e1245) + (0.0^e1345) - (0.0^e2345)
I (0.28925^e1) - (0.17599^e2) - (0.94094^e3)
(4.4559^e1) - (2.71111^e2) - (14.49492^e3) + (118.15387^e4) + (119.15387^e5)
-(0.0^e34) - (0.0^e35) + (0.0^e1234) + (0.0^e1235) + (0.0^e1245) - (0.0^e1345) - (0.0^e2345)
(0.0^e1234) + (0.0^e1235) - (0.0^e1245) - (0.0^e1345) - (0.0^e2345)
[3.94589021 4.85120396 0.30564779]
-(0.30565^e124) - (0.30565^e125) + (4.8512^e134) + (4.8512^e135) + (0.55711^e145) - (3.94589^e234) - (3.94589^e235) - (0.40756^e245) - (0.72355^e345)


In [124]:
print(M_dir_in_B4_q1)
print(I_in_B4)
I_in_B4 ^ M_dir_in_B4_q1 

(37.31403^e12) - (4.15248^e13) + (19.71304^e23)
(4.4559^e1) - (2.71111^e2) - (14.49492^e3) + (118.15387^e4) + (119.15387^e5)


-(464.2822^e123) + (4408.79667^e124) + (4446.11069^e125) - (490.63188^e134) - (494.78436^e135) + (2329.17195^e234) + (2348.88499^e235)

In [34]:
L_O = g3c_tools.meet(L_in_G_q1, L_in_G_q2)
print(L_O)
print(L_in_B4_q1.dual())
print(L_in_B4_q2.dual())

print(g3c_tools.meet(L_in_G_q1.dual(), L_in_G_q2.dual()))
# print(L)
print(L_in_G_q1.dual())
print(L_in_G_q2.dual())


(0.0^e4) + (0.0^e5) - (0.0^e124) - (0.0^e125) - (0.0^e134) - (0.0^e135) - (0.0^e145) + (0.0^e234) + (0.0^e235) - (0.0^e245) - (0.0^e345)
(37.31403^e12) - (4.15248^e13) - (40.97256^e14) - (40.97256^e15) + (19.71304^e23) - (452.00639^e24) - (452.00639^e25) + (71.94727^e34) + (71.94727^e35)
(13.4347^e12) - (7.56743^e13) + (73.26634^e14) + (73.26634^e15) - (10.34429^e23) + (90.07599^e24) + (90.07599^e25) + (5.6752^e34) + (5.6752^e35)
0
(3.07856^e12) + (33.21677^e13) - (189.16392^e14) - (189.16392^e15) - (26.17924^e23) + (107.07193^e24) + (107.07193^e25) - (453.32367^e34) - (453.32367^e35)
-(9.58812^e12) - (2.55136^e13) + (190.30129^e14) + (190.30129^e15) - (15.69459^e23) + (50.85682^e24) + (50.85682^e25) - (297.96735^e34) - (297.96735^e35)


In [78]:
(1.3^e1^e2) + 3*(e1^e3)

(1.3^e12) + (3.0^e13)