In [6]:
import numpy as np


Jt = np.random.uniform(size=(7,3))

Jtplus = np.linalg.pinv(Jt)
print(Jtplus.round(2))
print((Jtplus@Jt).round(2))

Jtplus_manual = np.linalg.inv(Jt.T @ Jt) @ Jt.T
print(Jtplus_manual.round(2))



[[-0.01  0.34  0.18  0.38 -0.16  0.61 -0.28]
 [-0.95  0.37  0.98 -0.32  0.03 -0.67  0.44]
 [ 1.31 -0.59 -0.98  0.11  0.46  0.2   0.11]]
[[ 1. -0. -0.]
 [ 0.  1.  0.]
 [-0. -0.  1.]]
[[-0.01  0.34  0.18  0.38 -0.16  0.61 -0.28]
 [-0.95  0.37  0.98 -0.32  0.03 -0.67  0.44]
 [ 1.31 -0.59 -0.98  0.11  0.46  0.2   0.11]]


In [2]:

from scipy.special import comb
def nb_k_face_zonotope(k, n, m):
    """Returns the number of k-dimensional faces of a zonotope in R^n with m generators in general position."""
    return 2 * comb(m, k) * sum([comb(m-k-1, i) for i in range(0, n-k)])


In [5]:
n, m = 2, 2
nb_k_face_zonotope(1, m, m) * m * 2

16.0